cull:
  users: false
hub:
  services:
    binder:
      oauth_redirect_uri: "http://127.0.0.1:8585/oauth_callback"
      oauth_client_id: "binder-oauth-client-test"

auth:
  type: dummy
  dummy:
    password: 'dummy'
