# This has secrets! Do not use this config for anything but local testing
# with minikube.

# the binder apiToken bit requires jupyterhub helm-chart v0.5.x

custom:
  cors:
    allowOrigin: "*"

hub:
  cookieSecret: "dummy-hub-cookie-secret"
  db:
    type: "sqlite-memory"
  services:
    binder:
      apiToken: "dummy-binder-secret-token"
  allowNamedServers: false
  extraConfig:
    10-binder-customisations: |
      # debug!
      c.JupyterHub.log_level = 10

proxy:
  secretToken: "dummy-proxy-secret-token"
  service:
    type: NodePort
    nodePorts:
      http: 30123
