# A JupyterHub Helm chart config for use whenever JupyterHub is deployed by
# itself.

debug:
  enabled: true

custom:
  cors:
    allowOrigin: "*"

hub:
  cookieSecret: "dummy-hub-cookie-secret"
  db:
    type: "sqlite-memory"
  services:
    binder:
      apiToken: "dummy-binder-secret-token"

proxy:
  secretToken: "dummy-proxy-secret-token"
  service:
    type: NodePort
    nodePorts:
      http: 30123
