# This has secrets! Do not use this config for anything but local testing
# with minikube.

# the binder apiToken bit requires jupyterhub helm-chart v0.5.x

rbac:
  enabled: true

custom:
  cors:
    allowOrigin: "*"

hub:
  cookieSecret: "36091e950f98f033aeae2520e2fe4c8599bc391598f910e510ad670765fbc1ff"
  db:
    type: "sqlite-memory"
  services:
    binder:
      admin: true
      apiToken: "aec7d32df938c0f55e54f09244a350cb29ea612907ed4f07be13d9553d18a8e4"
  allowNamedServers: false
  extraConfig:
    binder: |
      # image & token are set via spawn options
      from kubespawner import KubeSpawner
      from tornado import web

      # get cors config from values.custom.cors
      import z2jh
      cors = z2jh.get_config('custom.cors', {})

      class BinderSpawner(KubeSpawner):
        def get_args(self):
            args = [
                '--ip=0.0.0.0',
                '--port=%i' % self.port,
                '--NotebookApp.base_url=%s' % self.server.base_url,
                '--NotebookApp.token=%s' % self.user_options['token'],
                '--NotebookApp.trust_xheaders=True',
            ]
            allow_origin = cors.get('allowOrigin')
            if allow_origin:
                args.append('--NotebookApp.allow_origin=' + allow_origin)
            return args + self.args

        def start(self):
            if 'token' not in self.user_options:
              raise web.HTTPError(400, "token required")
            if 'image' not in self.user_options:
              raise web.HTTPError(400, "image required")

            self.image = self.user_options['image']
            return super().start()

        def get_env(self):
            env = super(BinderSpawner, self).get_env()
            if 'repo_url' in self.user_options:
                env['BINDER_REPO_URL'] = self.user_options['repo_url']
            for key in (
                    'binder_ref_url',
                    'binder_launch_host',
                    'binder_persistent_request',
                    'binder_request'):
                if key in self.user_options:
                    env[key.upper()] = self.user_options[key]
            return env

      # launch jupyter notebook instead of jupyterhub-singleuser
      c.JupyterHub.spawner_class = BinderSpawner

      # debug!
      c.JupyterHub.log_level = 10

singleuser:
  cmd: jupyter-notebook
  storage:
    type: none
  memory:
    guarantee: null
auth:
  type: custom
  custom:
    # disable login (users created exclusively via API)
    className: "nullauthenticator.NullAuthenticator"

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

proxy:
  # Another secret!
  secretToken: "443fa28905c209eaf5803f911de7748f443c78062767d9d28d514dc4fbefd843"
  service:
    type: NodePort
    nodePorts:
      http: 30123
