# Chart.yaml v2 reference: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: binderhub
version: 0.2.0-set.by.chartpress
description: A Helm chart to install BinderHub
keywords: [jupyter, jupyterhub, binderhub]
home: https://binderhub.readthedocs.io/en/latest/
sources: [https://github.com/jupyterhub/binderhub]
icon: https://jupyter.org/assets/hublogo.svg
kubeVersion: ">=1.17.0-0"
maintainers:
  # Since it is a requirement of Artifact Hub to have specific maintainers
  # listed, we have added some below, but in practice the entire JupyterHub team
  # contributes to the maintenance of this Helm chart. Please go ahead and add
  # yourself!
  - name: Erik Sundell
    email: erik@sundellopensource.se
