rbac:
  enabled: true

resources:
  requests:
    cpu: 0.2
    memory: 100Mi

cors: &cors
  allowOrigin: '*'

service:
  type: NodePort
  nodePort: 30901

config:
  BinderHub:
    hub_url: http://192.168.99.100:30902
    use_registry: false
    log_level: 10

jupyterhub:
  custom:
    cors: *cors
  rbac:
    enabled: true
  hub:
    resources:
      requests:
        cpu: 0.2
        memory: 100Mi
    cookieSecret: dummy-hub-cookie-secret
    db:
      type: sqlite-memory
    services:
      binder:
        apiToken: dummy-binder-secret-token

  proxy:
    secretToken: dummy-proxy-secret-token
    service:
      type: NodePort
      nodePorts:
        http: 30902

  singleuser:
    storage:
      type: none
    memory:
      guarantee: null
