# This config is used when both BinderHub and the JupyterHub it uses are
# deployed to a kubernetes cluster.
service:
  type: NodePort
  nodePort: 30901

config:
  
  ProxyRepoProvider:
    api_url: http://10.99.102.148:8000/api/projects
  BinderHub:

    # Use the internal host name for Pod to Pod communication
    # We can't use `hub_url` here because that is set to localhost which
    # works on the host but not from within a Pod
    hub_url_local: http://proxy-public
    use_registry: false
    log_level: 10
    cors_allow_origin: '*'

    # custom index page
    template_path: /etc/binderhub/custom/app/ui/public
    extra_static_path: /etc/binderhub/custom/app/ui/public
    extra_static_url_prefix: /extra_static/
    template_variables:
        EXTRA_STATIC_URL_PREFIX: "/extra_static/"


ingress:
  # Enabled to test the creation/update of the k8s Ingress resource, but not
  # used actively in our CI system.
  enabled: true

dind:
  # Not enabled to test the creation/update of the image-cleaner DaemonSet
  # resource because it also requires us to setup a container registry to test
  # against which we haven't. We currently only test this via
  # lint-and-validate-values.yaml that makes sure our rendered templates are
  # valid against a k8s api-server.
  enabled: false

# NOTE: This is a mirror of the jupyterhub section in
#       jupyterhub-chart-config.yaml in testing/local-binder-k8s-hub, keep these
#       two files synced please.
jupyterhub:
  debug:
    enabled: true

  hub:
    config:
      BinderSpawner:
        cors_allow_origin: "*"
    db:
      type: "sqlite-memory"

  proxy:
    service:
      type: NodePort
      nodePorts:
        http: 30902

  singleuser:
    storage:
      type: none
    memory:
      guarantee: null

initContainers:
  - name: git-clone-templates
    image: alpine/git
    args:
      - clone
      - --single-branch
      - --branch=master
      - --depth=1
      - --
      - https://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@github.com/chicago-cdac/opendata.git
      - /etc/binderhub/custom
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: custom-templates
        mountPath: /etc/binderhub/custom
extraVolumes:
  - name: custom-templates
    emptyDir: {}
extraVolumeMounts:
  - name: custom-templates
    mountPath: /etc/binderhub/custom