kind: ConfigMap
apiVersion: v1
metadata:
  name: binder-config
data:
{{- /* only pick relevant subset of values. Including too much here can trigger unnecessary binderhub pod restarts */}}
{{- $values := pick .Values "dind" "config" "extraConfig" }}
{{- /* make a copy to avoid modifying the original */ -}}
{{- $_ := set $values "config" (merge dict .Values.config) }}
{{- $_ := set $values.config "BinderHub" (merge dict .Values.config.BinderHub) }}
{{- /* trim secret values. Update here if new secrets are added! */ -}}
{{- if $values.config.GitHubRepoProvider }}
{{- $_ := set $values.config.GitHubRepoProvider (omit .Values.config.GitHubRepoProvider "client_secret" "access_token") }}
{{- end }}
{{- if $values.config.GitLabRepoProvider }}
{{- $_ := set $values.config.GitLabRepoProvider (omit .Values.config.GitLabRepoProvider "private_token" "access_token") }}
{{- end }}
  values.yaml: |
    {{- $values | toYaml | nindent 4 }}
