apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: binderhub-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: binder-pod
        {{ if .Values.deployment.labels -}}
        # Because toYaml + indent is super flaky
        {{ range $key, $value := .Values.deployment.labels -}}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      annotations:
        # This lets us autorestart when the configmap changes!
        checksum/config-map: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: binderhub
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: binder-config
      {{ if .Values.registry.enabled -}}
      - name: docker-secret
        secret:
          secretName: binder-secret
      {{ else -}}
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      {{- end }}
      containers:
      - name: binder-container
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        volumeMounts:
          - mountPath: /etc/binderhub/config/
            name: config
          {{ if .Values.registry.enabled -}}
          - mountPath: /root/.docker
            name: docker-secret
            readOnly: true
          {{ else -}}
          - mountPath: /var/run/docker.sock
            name: docker-socket
          {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12}}
        imagePullPolicy: IfNotPresent
        env:
        - name: BUILD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JUPYTERHUB_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: binder-secret
              key: "binder.hub-token"
        ports:
          - containerPort: 8585
            name: binder
