kind: Secret
apiVersion: v1
metadata:
  name: binder-secret
type: Opaque
stringData:
  {{- /* Stash away all Helm template values */}}
  values.yaml: |
    {{- .Values | toYaml | nindent 4 }}

  {{- /* Glob files to allow them to be mounted by the binderhub pod */}}
  {{- /* key=filename: value=content */}}
  {{- (.Files.Glob "files/*").AsConfig | nindent 2 }}
---
{{- if or .Values.config.BinderHub.use_registry .Values.config.BinderHub.buildDockerConfig }}
kind: Secret
apiVersion: v1
metadata:
  name: binder-build-docker-config
type: Opaque
data:
  config.json: {{ include "buildDockerConfig" . | b64enc | quote }}
{{- end }}
