apiVersion: v1
kind: Service
metadata:
  name: binder
  annotations: {{ toJson .Values.service.annotations }}
  labels: {{ toJson .Values.service.labels }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  selector:
    name: binder-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8585
      {{ if .Values.service.nodePort -}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
