name: eslint

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run ESLint on binderhub JS
      run: ./node_modules/.bin/eslint binderhub/static/js